python image_to_image_generation.py \
	--model_name_or_path "ogkalu/Comic-Diffusion" \
	--src_image_path "https://raw.githubusercontent.com/timothybrooks/instruct-pix2pix/main/imgs/example.jpg" \
	--prompts "turn him into cyborg" \
	--num_images_per_prompt 20 \
	--profiling_warmup_steps 3 \
	--profiling_steps 2 \
	--batch_size 2 \
	--guidance_scale 7.5 \
	--image_guidance_scale 1 \
	--num_inference_steps 10 \
	--image_save_dir stable_diffusion_images \
	--use_habana \
	--use_hpu_graphs \
	--gaudi_config Habana/stable-diffusion \
	--bf16
