accelerate launch train_text_to_image_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="lambdalabs/pokemon-blip-captions" \
  --resolution=512 \
  --center_crop \
  --random_flip \
  --proportion_empty_prompts=0.2 \
  --train_batch_size=4 \
  --gradient_accumulation_steps=1 \
  --max_train_steps=2500 \
  --use_8bit_adam \
  --learning_rate=1e-06 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --output_dir="sdxl-pokemon-model" \
  --throughput_warmup_steps 3 \
  --dataloader_num_workers 8 \
  --mixed_precision="fp16" \
  --validation_prompt="a robotic cat with wings" \
  --validation_epochs 12 \
  --checkpointing_steps=2500 \
  --logging_step 10 2>&1 | tee a100_1x_fp16.log
