apiVersion: "batch/v1"
kind: Job
metadata:
  name: {{ .Release.Name }}-gaudijob
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostIPC: {{ .Values.hostIPC }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-gaudijob-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          {{- if .Values.secret.encodedToken}}
          - name: HF_TOKEN_PATH
            value: {{ .Values.secret.secretMountPath }}/token
          {{- end }}
            {{- toYaml .Values.env | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: pvc-volume
            mountPath: {{ .Values.storage.pvcMountPath }}
          {{- if .Values.secret.encodedToken}}
          - name: secret-volume
            mountPath: {{ .Values.secret.secretMountPath }}
          {{- end }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
      {{- if .Values.secret.encodedToken}}
      - name: secret-volume
        secret:
          secretName: {{ .Release.Name }}-secret
      {{- end }}

