apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- with .Values.storage.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.storage.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
