name: Build PR documentation

on:
  pull_request:
    branches: [ main ]
    paths:
      - "optimum/**.py"
      - "docs/**"
      - ".github/workflows/build_pr_documentation.yml"
      - ".github/workflows/delete_doc_comment.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/doc-builder'
          path: doc-builder

      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum-habana'
          path: optimum-habana

      - name: Setup environment
        run: |
          pip uninstall -y doc-builder
          cd doc-builder
          git pull origin main
          pip install .
          pip install black
          cd ..

      - name: Make documentation
        run: |
          cd optimum-habana
          make doc BUILD_DIR=habana-doc-build VERSION=pr_$PR_NUMBER COMMIT_SHA_SUBPACKAGE=$COMMIT_SHA CLONE_URL=$PR_CLONE_URL
          cd ..

      - name: Save commit_sha & pr_number
        run: |
          echo ${{ env.COMMIT_SHA }} > ./habana-doc-build/commit_sha
          echo ${{ env.PR_NUMBER }} > ./habana-doc-build/pr_number

      - uses: actions/upload-artifact@v3
        with:
          name: doc-build-artifact
          path: habana-doc-build/
