name: Delete PR documentation

on:
  pull_request:
    types: [ closed ]
    paths:
      - "optimum/**.py"
      - "docs/**"
      - ".github/workflows/build_pr_documentation.yml"
      - ".github/workflows/delete_doc_comment.yml"


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@main
    with:
      pr_number: ${{ github.event.number }}
      package: optimum-habana
